### ISSUE TITLE
Verify if retry logic works and sets error code if it doesn't

### ISSUE THREAD

**Issue by vaind** [getsentry/symbol-collector#167]
Doesn't seem to work from the log - there's just a log about a failed upload but no log about trying again (and succeeding).

See 
https://github.com/getsentry/sentry-dart/actions/runs/6649991569/job/18069373897#step:6:4427

```
FINER: 2023-10-26 06:11:27.528091:    info: System.Net.Http.HttpClient.ISymbolClient.LogicalHandler[100]
FINER: 2023-10-26 06:11:27.528112:          Start processing HTTP request POST https://symbol-collector.services.sentry.io/symbol/batch/acb0d8eb-c6f6-46a5-b1c8-176ecb051369/upload
FINER: 2023-10-26 06:11:27.528853:    info: System.Net.Http.HttpClient.ISymbolClient.ClientHandler[100]
FINER: 2023-10-26 06:11:27.528889:          Sending HTTP request POST https://symbol-collector.services.sentry.io/symbol/batch/acb0d8eb-c6f6-46a5-b1c8-176ecb051369/upload
FINER: 2023-10-26 06:11:36.642136:    info: System.Net.Http.HttpClient.ISymbolClient.ClientHandler[101]
FINER: 2023-10-26 06:11:36.642180:          Received HTTP response headers after 9113.6459ms - 400
FINER: 2023-10-26 06:11:36.642633:    info: System.Net.Http.HttpClient.ISymbolClient.LogicalHandler[101]
FINER: 2023-10-26 06:11:36.642644:          End processing HTTP request after 9114.1039ms - 400
FINER: 2023-10-26 06:11:36.654732:    warn: SymbolCollector.Core.SymbolClient[0]
FINER: 2023-10-26 06:11:36.654765:          Failed to upload file
FINER: 2023-10-26 06:11:36.654773:          System.InvalidOperationException: Failed uploading file. Server response: BadRequest
FINER: 2023-10-26 06:11:36.654780:             at SymbolCollector.Core.SymbolClient.ThrowOnUnsuccessfulResponse(String message, HttpResponseMessage checkResponse)
FINER: 2023-10-26 06:11:36.654788:             at SymbolCollector.Core.SymbolClient.<>c__DisplayClass9_0.<<Upload>g__Upload|1>d.MoveNext()
FINER: 2023-10-26 06:11:36.723514:    warn: SymbolCollector.Core.Client[0]
FINER: 2023-10-26 06:11:36.723582:          Failed to upload. Failure count: 1.
FINER: 2023-10-26 06:11:36.723595:          System.InvalidOperationException: Failed uploading file. Server response: BadRequest
FINER: 2023-10-26 06:11:36.723610:             at SymbolCollector.Core.SymbolClient.ThrowOnUnsuccessfulResponse(String message, HttpResponseMessage checkResponse)
FINER: 2023-10-26 06:11:36.723625:             at SymbolCollector.Core.SymbolClient.<>c__DisplayClass9_0.<<Upload>g__Upload|1>d.MoveNext()
FINER: 2023-10-26 06:11:36.723636:          --- End of stack trace from previous location ---
FINER: 2023-10-26 06:11:36.723646:             at SymbolCollector.Core.SymbolClient.<>c__DisplayClass9_0.<<Upload>g__Upload|1>d.MoveNext()
FINER: 2023-10-26 06:11:36.723660:          --- End of stack trace from previous location ---
FINER: 2023-10-26 06:11:36.723670:             at SymbolCollector.Core.SymbolClient.Upload(Guid batchId, String unifiedId, String hash, String fileName, Func`1 fileFactory, CancellationToken token)
FINER: 2023-10-26 06:11:36.723681:             at SymbolCollector.Core.Client.UploadAsync(Guid batchId, ObjectFileResult objectFileResult, CancellationToken cancellationToken)
FINER: 2023-10-26 06:11:36.723692:             at SymbolCollector.Core.Client.UploadFilesAsync(Guid batchId, String path, CancellationToken cancellationToken)
```

_Originally posted by @vaind in https://github.com/getsentry/sentry-dart/pull/1673#discussion_r1373476607_

**Comment by bruno-garcia** [comment]
This one we should fix
