### ISSUE TITLE
Cap number of symlink follow ups

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/symbol-collector#89]
```
System.IO.IOException: Too many levels of symbolic links
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at SymbolCollector.Core.Client.<>c__DisplayClass11_0.<<UploadAllPathsAsync>g__SafeGetDirectories|7>d.MoveNext()
   at SymbolCollector.Core.Client.<>c__DisplayClass11_0.<<UploadAllPathsAsync>g__SafeGetDirectories|7>d.MoveNext()
   at SymbolCollector.Core.Client.<>c__DisplayClass11_0.<<UploadAllPathsAsync>g__SafeGetDirectories|7>d.MoveNext()
   at SymbolCollector.Core.Client.<>c__DisplayClass11_0.<<UploadAllPathsAsync>g__SafeGetDirectories|7>d.MoveNext()
   at SymbolCollector.Core.Client.<>c__DisplayClass11_0.<<UploadAllPathsAsync>g__SafeGetDirectories|7>d.MoveNext()
   at SymbolCollector.Core.Client.<>c__DisplayClass11_0.<<UploadAllPathsAsync>g__SafeGetDirectories|7>d.MoveNext()
   at SymbolCollector.Core.Client.<>c__DisplayClass11_0.<<UploadAllPathsAsync>g__SafeGetDirectories|7>d.MoveNext()
   at SymbolCollector.Core.Client.<>c__DisplayClass11_0.<<UploadAllPathsAsync>g__SafeGetDirectories|7>d.MoveNext()
   at SymbolCollector.Core.Client.<>c__DisplayClass11_0.<<UploadAllPathsAsync>g__SafeGetDirectories|7>d.MoveNext()
   at SymbolCollector.Core.Client.<>c__DisplayClass11_0.<<UploadAllPathsAsync>g__SafeGetDirectories|7>d.MoveNext()
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext() 
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at SymbolCollector.Core.Client.UploadAllPathsAsync(String friendlyName, BatchType type, IEnumerable`1 topLevelPaths, CancellationToken cancellationToken)
   at SymbolCollector.Console.ConsoleUploader.StartUploadSymbols(IEnumerable`1 paths, String bundleId, CancellationToken token)
   at SymbolCollector.Console.Program.Run(Args args)
   at SymbolCollector.Console.Program.Main(String upload, String check, String path, String symsorter, String bundleId, String batchType, Boolean dryrun, Uri serverEndpoint)
```

**Comment by stephanie-anderson** [comment]
**Why was this issue closed?**

This issue hasn't been touched recently and no longer seems relevant. 
Hence, we're closing it to maintain a clean and transparent backlog.

Please feel free to leave a comment if you think this issue should be reopened.
